---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ThinkPad E475.
--- DateTime: 2019/5/8 19:35
---

local work_config = {}
work_config.work_area_ox = -5
work_config.work_area_oy = -5
work_config.work_area_oz = -5
work_config.work_area_sx = 10
work_config.work_area_sy = 10
work_config.work_area_sz = 8
return work_config