---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ThinkPad E475.
--- DateTime: 2019/4/4 20:16
---

sm1 = require("submodule1")
sm2 = require("submodule2")
module = {}

module["submodule1"] = sm1
module["submodule2"] = sm2

return module