---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ThinkPad E475.
--- DateTime: 2019/4/24 10:46
---

package.path = "obj\\?.lua;util\\?.lua;config\\?.lua;"..package.path
require("util.robot")

--print(move(5,-1,0))
run()