---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ThinkPad E475.
--- DateTime: 2019/4/4 20:24
---

module = {}
---
--- 测试函数3
---
function module.fun3()
    print("sub fun3")
end
---
--- 测试函数4
---
function module.fun4()
    print("sub fun4")
end

return module