---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ThinkPad E475.
--- DateTime: 2019/4/4 20:24
---

module = {}

function module.fun1()
    print("sub fun1")
end

function module.fun2()
    print("sub fun2")
end

return module