---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ThinkPad E475.
--- DateTime: 2019/4/13 23:48
---

package.path = "obj\\?.lua;util\\?.lua"..package.path

--AstarPathing = require("util.AstarPathing")
--
--printMap()
--path = getPath(0,3,7,3)
--if path then
--    drawPath(path)
--    print("\n-----------------------------------\n")
--    printMap()
--else
--    print("faild!")
--end

--PathingFor3d = require("util.PathingFor3d")
--
--printMap()
--path = getPath(0,0,0,3,3,3)
--if path then
--    drawPath(path)
--    print("\n-----------------------------------\n")
--    printMap()
--else
--    print("faild!")
--end


astar = require("util.AstarPathingWithDirection")
map = {
    ["0,0"]={
        [0]=0,0,0,0,0,0,0,0,
        0,0,0,0,0,1,0,0,
        0,0,0,1,0,1,0,0,
        0,0,0,1,0,1,0,0,
        0,0,0,0,0,1,0,0,
        0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,
        1,1,1,1,1,0,1,0,},
    ["0,1"]={
        [0]=0,0,0,0,0,0,0,0,
        0,0,0,0,0,1,1,0,
        0,0,0,1,0,0,0,0,
        0,0,0,1,0,0,0,0,
        0,0,0,1,0,0,0,0,
        0,1,1,1,1,1,1,0,
        0,0,0,0,0,0,0,0,
        0,0,0,0,0,0,0,0,}
}
path = astar.getPath(map,1,1,4,14,1)
if path then
    astar.printMap(path)
else
    astar.printMap(path)
    print("faild!")
end

